// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCee9_8VHo8ueYRkYnmvG8M17pk_PUUa2I',
    appId: '1:594173825995:web:882fedc29a8c871e09dc4e',
    messagingSenderId: '594173825995',
    projectId: 'fasum-kristopherowen',
    authDomain: 'fasum-kristopherowen.firebaseapp.com',
    databaseURL: 'https://fasum-kristopherowen-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-kristopherowen.firebasestorage.app',
    measurementId: 'G-F23GLY8KEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvVZ4gNHUmvus29FsCMty1wHPHY0ZKYc',
    appId: '1:594173825995:android:a3701898cd8d106c09dc4e',
    messagingSenderId: '594173825995',
    projectId: 'fasum-kristopherowen',
    databaseURL: 'https://fasum-kristopherowen-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-kristopherowen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6BDKMwrfYNSrYnKo44oRa7AlYzhsRNTE',
    appId: '1:594173825995:ios:bc49fc2b1147057709dc4e',
    messagingSenderId: '594173825995',
    projectId: 'fasum-kristopherowen',
    databaseURL: 'https://fasum-kristopherowen-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-kristopherowen.firebasestorage.app',
    iosBundleId: 'com.example.fasumKristopherowen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6BDKMwrfYNSrYnKo44oRa7AlYzhsRNTE',
    appId: '1:594173825995:ios:bc49fc2b1147057709dc4e',
    messagingSenderId: '594173825995',
    projectId: 'fasum-kristopherowen',
    databaseURL: 'https://fasum-kristopherowen-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-kristopherowen.firebasestorage.app',
    iosBundleId: 'com.example.fasumKristopherowen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCee9_8VHo8ueYRkYnmvG8M17pk_PUUa2I',
    appId: '1:594173825995:web:63fad92269902ddf09dc4e',
    messagingSenderId: '594173825995',
    projectId: 'fasum-kristopherowen',
    authDomain: 'fasum-kristopherowen.firebaseapp.com',
    databaseURL: 'https://fasum-kristopherowen-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-kristopherowen.firebasestorage.app',
    measurementId: 'G-P54VDNF34J',
  );
}
